server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.98.163.117:3306/ming_blog
    username: root
    password: 123456
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 47.98.163.117

mybatis:
  config-location:  classpath:mybatis-config.xml
  type-aliases-package: com.heiio.bookredis.model

logging:
  level:
    com.heiio.bookredis.mapper.*: debug
