spring:
  redis:
    host: 47.98.163.117
  cache:
    type: redis
server:
  port: 9090

mybatis:
  config-location:  classpath:mybatis-config.xml
  type-aliases-package: com.heiio.bookredis.model

logging:
  level:
    com.heiio.bookredis.mapper.*: debug
